name: Code style check

on: [pull_request]

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Lint
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: "./src"
          exclude: "./src/libcfxaddr"
          extensions: "h,c"
          clangFormatVersion: 13
